- name: Crear backup
  env:
    DB_HOST: db.puehhniulzfadfzydxeu.supabase.co
    DB_USER: postgres
    DB_PASS: ${{ secrets.DB_PASSWORD }}
    DB_NAME: postgres
  run: |
    set -e

    mkdir -p backups

    FILE="backup-$(date +'%Y-%m-%d_%H-%M').dump"

    pg_dump \
      -h $DB_HOST \
      -U $DB_USER \
      -d $DB_NAME \
      --no-owner \
      --no-privileges \
      --format=custom \
      -f "backups/$FILE"

    gzip "backups/$FILE"